
dataset:
  name: super_glue.boolq
  path: # dataset in huggingface doesn't need path

plm:
  model_name: t5
  model_path: t5-large
  optimize:
    freeze_para: False
    lr: 1.0e-5
    weight_decay: 0.0
    scheduler:
      type: 
      num_warmup_steps: 500

dataloader:
  max_seq_length: 256  # max_seq_length 
  decoder_max_length: 3 # the decoder max length to truncate decoder input sequence
                    # if it is an encoder-decoder architecture. Note that it's not equavalent
                    # to generation.max_length which is used merely in the generation phase.
  truncate_method: "head" # choosing from balanced, head, tail
  decode_from_pad: true

train:
  batch_size: 8
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  num_epochs:
  num_training_steps: 1000
  # clean: True




test:
  batch_size: 16

dev:
  batch_size: 16

template: manual_template
manual_template:
  choice: 0
  file_path:  distillation/booq_soft_template_no_hard_token.txt


verbalizer: manual_verbalizer
manual_verbalizer:
  choice: 0
  file_path: scripts/SuperGLUE/BoolQ/manual_verbalizer.txt
  


learning_setting: few_shot


few_shot:
  parent_config: learning_setting
  few_shot_sampling: sampling_from_train
  

sampling_from_train:
  parent_config: few_shot_sampling
  num_examples_per_label: 32
  also_sample_dev: True
  num_examples_per_label_dev: 32
  seed:
    - 123
    
environment:
  num_gpus: 5
  cuda_visible_devices: [0,3,4,6,7]
  local_rank: 0
  model_parallel: True
  device_map: